#!/usr/bin/env bash

export TOP=`pwd`
export NAME=`basename $TOP`

cd ../pygame-package-0.9.3
./build.py --dir $TOP --package com.pygame.$NAME --name $NAME --icon $TOP/icon.png --presplash $TOP/splash.jpg --version 1.0 --orientation portrait --with-PIL release
